common2d.o:	common2d.o
	gcc -c common2d.h common2d.cpp

Program01: main.o common2d.o
	gcc -o Program main.o common2d.o

main.o:	01.cpp
	g++ -c 01.cpp

Program02: main.o common2d.o
	gcc -o Program main.o common2d.o

main.o:	02.cpp
	g++ -c 02.cpp

Program03: main.o common2d.o
	gcc -o Program main.o common2d.o

main.o:	03.cpp
	g++ -c 03.cpp

Program0*: main.o common2d.o
	gcc -o Program main.o common2d.o

main.o:	0*.cpp
	g++ -c 0*.cpp

